### ISSUE TITLE
3 fingers tap (Magic mouse) doesn't work with 3 fingers tap to look up (trackpad)

### ISSUE THREAD

**Issue by longnd** [LoPablo/MiddleClick#6]
if enabling 3 fingers tap to lookup dictionary (trackpad) & 3 fingers tap for middle click (Magic mouse), the 3 fingers tap to lookup doesn't work, the lookup window just blinks and disappear

**Comment by LoPablo** [comment]
If I understand you correctly, when you use the 3 finger tap option in MiddleClick, because you want to use it with the MagicMouse, the 3 Finger tap to lookup is not working on trackpad anymore.

This behavior ist natural, since MiddleClick is looking for a three finger tap on all of the present touch devices. It does not differentiate between MagicMouse and Trackpad and is then also issuing a MiddleClick.

**Comment by longnd** [comment]
ok, now I know the reason. So there is no way to fix it.
I'll close this issue.

Thanks
